#!/usr/bin/env bash
#this script copies the required libraries into Fiji installation directory

if [ ! $# -eq 1 ]; then
	echo "provide path to your Fiji installation"
	exit 1
fi

DIR=`greadlink -f $1`
cp -v target/module-assembly-bin/lib/*.jar $DIR/jars/
