#!/usr/bin/env bash
#this script build required libraries and copies into Fiji installation directory
FIJI_APP=ImageJ-linux64
UPDATE_SITE=P2E-IT4Innovations
mvn clean package -Denforcer.skip=true

DIR=`readlink -f $1`
OLD_DIR=`readlink -f .`
cd $DIR/jars
cd $OLD_DIR
cp target/hpc-datastore-*-SNAPSHOT.jar target/module-assembly-bin/lib/*.jar $DIR/jars/
#$DIR/$FIJI_APP --update upload-complete-site $UPDATE_SITE
