#!/usr/bin/env bash
#this script copies the required libraries into Fiji installation directory

if [ ! $# -eq 1 ]; then
	echo "provide path to your Fiji installation"
	exit 1
fi

DIR=`readlink -f $1`
OLD_DIR=`readlink -f .`
cd $DIR/jars
cd $OLD_DIR
cp -v target/module-assembly-bin/lib/*.jar $DIR/jars/
