#!/usr/bin/env bash
UUID=`cat uuid.txt`

printf "0: %.8x" 64 | xxd -r -g0 > input.bin
printf "0: %.8x" 64 | xxd -r -g0 >> input.bin
printf "0: %.8x" 64 | xxd -r -g0 >> input.bin
head -c 2097152 /dev/urandom >> input.bin

printf "0: %.8x" 32 | xxd -r -g0 >> input.bin
printf "0: %.8x" 32 | xxd -r -g0 >> input.bin
printf "0: %.8x" 32 | xxd -r -g0 >> input.bin
head -c 262144 /dev/urandom >> input.bin

REDIRECT=`curl -X GET -w %{redirect_url}  http://localhost:8080/datasets/$UUID/1/1/1/latest-for-writing-only?timeout=10000`
echo $REDIRECT'0/0/0/0/0/0/'
sleep 15

curl -X POST -c cookies.txt --data-binary "@input.bin" -H "Content-Type: application/octet-stream" $REDIRECT'0/0/0/0/0/0/0/1/0/0/0/0/'
curl -X GET -b cookies.txt $REDIRECT'0/0/0/0/0/0/0/1/0/0/0/0/' --output output.bin


diff input.bin output.bin
# rm input.bin output.bin cookies.txt
echo
