#!/usr/bin/env bash
UUID=`cat uuid.txt`
printf "0: %.8x" 32 | xxd -r -g0 > input.bin
printf "0: %.8x" 32 | xxd -r -g0 >> input.bin
printf "0: %.8x" 32 | xxd -r -g0 >> input.bin
head -c 262144 /dev/urandom >> input.bin
curl -X GET  http://localhost:8080/datasets/$UUID/1/1/1/latest-for-writing-only?timeout=10000

#curl -X GET -c cookies.txt http://localhost:8080/$UUID/1/1/1/latest/write
#curl -X POST -b cookies.txt --data-binary "@input.bin" -H "Content-Type: application/octet-stream" http://localhost:8080/$UUID/2/2/1/latest/0/0/0/0/0/0/
#curl -X GET -b cookies.txt  http://localhost:8080/$UUID/2/2/1/latest/0/0/0/0/0/0/ --output output.bin
diff input.bin output.bin
rm input.bin output.bin cookies.txt
echo
