#!/usr/bin/env bash
UUID=`cat uuid.txt`

voxelSize=8
x=64
y=64
z=1
posX=1
posY=0
posZ=0
printf "0: %.8x" $x | xxd -r -g0 > input.bin
printf "0: %.8x" $y | xxd -r -g0 >> input.bin
printf "0: %.8x" $z | xxd -r -g0 >> input.bin
head -c $((x*y*z*voxelSize)) /dev/urandom >> input.bin

x=64
y=64
z=1
pozX=1
pozY=1
pozZ=0
printf "0: %.8x" $x | xxd -r -g0 >> input.bin
printf "0: %.8x" $y | xxd -r -g0 >> input.bin
printf "0: %.8x" $z | xxd -r -g0 >> input.bin
head -c $((x*y*z*voxelSize)) /dev/urandom >> input.bin

REDIRECT=`curl -X GET -w %{redirect_url}  http://localhost:8080/datasets/$UUID/1/1/1/latest/read-write?timeout=20000`
echo "started dedicated server at $REDIRECT"
echo -n "giving it 5sec pace time: "
sleep 1; echo -n "."
sleep 1; echo -n "."
sleep 1; echo -n "."
sleep 1; echo -n "."
sleep 1; echo    "."

curl -X POST -c cookies.txt --data-binary "@input.bin" -H "Content-Type: application/octet-stream" $REDIRECT"$posX/$posY/$posZ/0/0/0/$pozX/$pozY/$pozZ/0/0/0/"
curl -X GET -b cookies.txt $REDIRECT"$posX/$posY/$posZ/0/0/0/$pozX/$pozY/$pozZ/0/0/0/" --output output.bin


diff input.bin output.bin
# rm input.bin output.bin cookies.txt
echo
