#!/usr/bin/env bash
head -c 40000 /dev/urandom > input.bin
curl -X POST --data-binary "@input.bin" -H "Content-Type: application/octet-stream" http://localhost:9080/123/2/2/1/latest/0/0/0/0/0/0/0/1/0/0/0/0/
curl -X GET http://localhost:9080/123/2/2/1/latest/0/0/0/0/0/0/0/1/0/0/0/0/ --output output.bin
diff input.bin output.bin
rm input.bin output.bin
echo
